[project]
name = "buou-grid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.9.3",
    "asyncio==3.4.3",
    "ccxt>=4.5",
    "python-dotenv>=1.0.0",
    "websockets>=12.0",
]
